In [4]:
import tensorflow as tf

In [5]:
tens=tf.constant(value='My first program using tensorflow')

In [6]:
tens

<tf.Tensor 'Const_1:0' shape=() dtype=string>

In [7]:
type(tens)

tensorflow.python.framework.ops.Tensor

In [8]:
sess=tf.Session()

In [9]:
output=sess.run(tens)

In [10]:
sess.close()

In [11]:
output

b'My first program using tensorflow'

In [12]:
with tf.Session() as sess:
    output1=sess.run(tens)

In [13]:
output1

b'My first program using tensorflow'

In [14]:
val1=tf.constant(value=100,name="x",dtype=tf.int32)

In [15]:
val1

<tf.Tensor 'x:0' shape=() dtype=int32>

In [17]:
tf.rank(val1)

<tf.Tensor 'Rank:0' shape=() dtype=int32>

In [18]:
val2=tf.constant(value=200,name="y",dtype=tf.int32)

In [19]:
with tf.Session() as sess:
    output2=sess.run(val1)
    val3=tf.add(val1,val2,name="add")
    val4=tf.subtract(val2,val1,name="sub")
    val5=tf.add(val3,val4,name="z")
    val6=tf.cast(val5,tf.float32)
    val7=tf.to_float(val5)
    output2,output3,output4,output5=sess.run([val1,val5,val6,val7])
    print(output2,output3,output4,output5)

100 400 400.0 400.0


In [22]:
x=tf.fill(value=5,dims=(3,4))

In [23]:
y=tf.constant([1,2,4,8,6,4,9,1,3,5,7,3],shape=(3,4))

In [24]:
y1=tf.constant([1,2,4,8,6,4,9,1,3,5,7,3],shape=(4,3))

In [25]:
y2=tf.zeros(shape=(2,3),dtype=tf.float32)

In [26]:
with tf.Session() as sess:
    z=tf.add(x,y)
    z4=tf.subtract(x,y)
    z5=tf.multiply(x,y)
    z6=tf.matmul(x,y1)
    z6=tf.div(x,y)
    z7=tf.divide(x,y)
    z8=tf.pow(y,2)
    z9=tf.concat([x,y],axis=0)
    z10=tf.concat([x,y],axis=1)
    z1=tf.greater_equal(y,6)
    z11=tf.greater(y,6)
    z12=tf.less_equal(y,6)
    z13=tf.less(y,6)
    z14=tf.equal(y,6)
    z2=tf.reduce_all(tf.greater_equal(y,1))
    print("X: \n",sess.run(x))
    print("Y:\n",sess.run(y))
    out,out1,out2,out3,out4,out5,out6,out7,out8,out9,out10,out11,out12,out13=sess.run([z,z1,z4,z5,z6,z7,z8,z9,z10,z11,
                                                                                       z12,z13,z14,z2])
    print('\n')
    print("Zeros:\n",sess.run(y2))
    print("Number of dimensions of tensor x & y: ",sess.run(tf.rank(x)),",",sess.run(tf.rank(y)))
    print("\nAdd:\n", out)
    print("Subtract: \n",out2)
    print("Multiply: \n",out3)
    print("Elementwise Division:\n",out4)
    print("Division: \n",out5)
    print("Power: \n",out6)
    print("Greater than or Equal to 6: \n",out1)
    print("Greater than 6: \n",out9)
    print("Less than or Equal to 6: \n",out10)
    print("Less than 6: \n",out11)
    print("Equal to 6: \n",out12)
    print("Concatenation by rows: \n",out7)
    print("Concatenation by columns: \n",out8)
    print("All values greater than or equal to 1: \n",out13)

X: 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Y:
 [[1 2 4 8]
 [6 4 9 1]
 [3 5 7 3]]


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Number of dimensions of tensor x & y:  2 , 2

Add:
 [[ 6  7  9 13]
 [11  9 14  6]
 [ 8 10 12  8]]
Subtract: 
 [[ 4  3  1 -3]
 [-1  1 -4  4]
 [ 2  0 -2  2]]
Multiply: 
 [[ 5 10 20 40]
 [30 20 45  5]
 [15 25 35 15]]
Elementwise Division:
 [[5 2 1 0]
 [0 1 0 5]
 [1 1 0 1]]
Division: 
 [[5.         2.5        1.25       0.625     ]
 [0.83333333 1.25       0.55555556 5.        ]
 [1.66666667 1.         0.71428571 1.66666667]]
Power: 
 [[ 1  4 16 64]
 [36 16 81  1]
 [ 9 25 49  9]]
Greater than or Equal to 6: 
 [[False False False  True]
 [ True False  True False]
 [False False  True False]]
Greater than 6: 
 [[False False False  True]
 [False False  True False]
 [False False  True False]]
Less than or Equal to 6: 
 [[ True  True  True False]
 [ True  True False  True]
 [ True  True False  True]]
Less than 6: 
 [[ True  True  True False]
 [False  True False  True]
 [ True  True Fals